// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Comment struct {
	ID        int32     `json:"id"`
	PostID    int32     `json:"post_id"`
	UserID    int32     `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Neighborhood struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	Lat      string         `json:"lat"`
	Lng      string         `json:"lng"`
	RadiusKm sql.NullString `json:"radius_km"`
}

type Post struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Category  string       `json:"category"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	ImageUrl  []string     `json:"image_url"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

type User struct {
	ID        int32          `json:"id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
