// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  user_id, category, title, content, image_url, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, category, title, content, image_url, created_at, expires_at
`

type CreatePostParams struct {
	UserID    int32        `json:"user_id"`
	Category  string       `json:"category"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	ImageUrl  []string     `json:"image_url"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.UserID,
		arg.Category,
		arg.Title,
		arg.Content,
		pq.Array(arg.ImageUrl),
		arg.ExpiresAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Title,
		&i.Content,
		pq.Array(&i.ImageUrl),
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
